[package]

name = "rusty-build-light"
version = "0.0.1"
authors = [ "dboone <boonesoftware@gmail.com>" ]

[dependencies]
chrono = "0.2"
rustc-serialize = "0.3"
serial = "0.3"

[dependencies.curl]
git = "https://github.com/carllerche/curl-rust"